version: "3.7"

services:

  isbn-stacks-kofu:
    hostname: isbn-stacks-kofu
    build:
      context: isbn-stacks-rest-kofu-mvc-reactive/.
    ports:
      - "8080:8080"
    restart: on-failure

  isbn-stacks-reactive:
    hostname: isbn-stacks-reactive
    build:
      context: isbn-stacks-rest-traditional-mvc-reactive/.
    ports:
      - "8081:8081"
    restart: on-failure

  isbn-stacks-mvc:
    hostname: isbn-stacks-mvc
    build:
      context: isbn-stacks-rest-traditional-mvc-non-reactive/.
    ports:
      - "8082:8082"
    restart: on-failure

