services:
  e2e-electron:
    image: "cypress/included:14.0.1"
    working_dir: /e2e
    command: "--browser electron --config-file cypress.pipeline.config.ts"
    volumes:
      - ./e2e:/e2e

  e2e-chrome:
    image: "cypress/included:14.0.1"
    working_dir: /e2e
    command: "--browser chrome --config-file cypress.pipeline.config.ts"
    volumes:
      - ./e2e:/e2e

  e2e-firefox:
    image: "cypress/included:14.0.1"
    working_dir: /e2e
    command: "--browser firefox --config-file cypress.pipeline.config.ts"
    volumes:
      - ./e2e:/e2e

  e2e-edge:
    image: "cypress/included:14.0.1"
    working_dir: /e2e
    command: "--browser edge --config-file cypress.pipeline.config.ts"
    volumes:
      - ./e2e:/e2e
